server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    mongodb:
      uri: "mongodb+srv://jonathan:eaglerating@cluster0.7cjsxez.mongodb.net/EagleRating"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
knife4j:
  enable: true  #是否开启Swagger
  cors: true
  basic:
    enable: true  #进入界面是否需要账号密码
    username: admin
    password: 123456
  setting:
    # Knife4j默认显示中文(zh-CN),如果开发者想直接显示英文(en-US)，在通过该配置进行设置即可
    language: en-US