server:
  port: 8080
  servlet:
    context-path: /
    max-file-size: 20MB
    max-request-size: 20MB
    multipart:
        enabled: True
        max-file-size: 20MB
        max-request-size: 20MB
  tomcat:
    max-http-form-post-size: 20MB

spring:
  data:
    mongodb:
      uri: ${mongo_DB_uri}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: eaglerating.astar@gmail.com
    password: prpriaikwvedneer
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
knife4j:
  enable: true
  cors: true
  basic:
    username: admin
    password: 123
    enable: true
  setting:
    language: en-US
