server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    mongodb:
      uri: "mongodb+srv://henry:eaglerating12345@cluster0.7cjsxez.mongodb.net/EagleRating"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: eaglerating.astar@gmail.com  # Replace with your Gmail email address
    password: prpriaikwvedneer
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
knife4j:
  enable: true  #是否开启Swagger
  cors: true
  basic:
    username: admin
    password: 123
    enable: true #开启认证
  setting:
    # Knife4j默认显示中文(zh-CN),如果开发者想直接显示英文(en-US)，在通过该配置进行设置即可
    language: en-US
    # 是否启用Host
