server:
  port: 8080
  servlet:
    context-path: /
spring:
  data:
    mongodb:
      uri: ${mongo_DB_uri}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
knife4j:
  enable: true
  cors: true
  basic:
    username: admin
    password: 123
    enable: true
  setting:
    language: en-US
